version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      network: host
    image: backend-app
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    
  frontend:
    build:
      context: ./Frontent/frontend-app
      dockerfile: Dockerfile
      network: host
    image: frontend-app
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
