version: '3.9'

# Configuration spécifique pour le développement local
services:
  backend:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend:/app
    environment:
      - DEBUG=True
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./Frontent/frontend-app
      target: builder
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./Frontent/frontend-app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000

  db:
    ports:
      - "5432:5432"
