apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: app-kid
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "backend,backend.app-kid.svc.cluster.local"
  CORS_ALLOWED_ORIGINS: "http://frontend,http://frontend.app-kid.svc.cluster.local"
