apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-kid

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: kid-livraison
  app.kubernetes.io/managed-by: argocd

images:
  - name: ghcr.io/VOTRE_ORG/kid-backend
    newTag: latest
  - name: ghcr.io/VOTRE_ORG/kid-frontend
    newTag: latest
