apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kid-livraison-ingress
  namespace: app-kid-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: dev.kid-livraison.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: dev-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-frontend
                port:
                  number: 80
